
SEPARATOR = "|"
TERMINATOR = "\r\n"
TEAM_NAME = "DogeTeam"
BOARD_SIZE = 31

MAP = {
	'R': 0,
	'E': 3,
	'H': 1,
	'S': 2
}

DIR_TOP = "T"
DIR_BOTTOM = "B"
DIR_RIGHT = "R"
DIR_LEFT = "L"

CMD_MOVE = "MOVE"
CMD_TEAMS = "TEAMS"
CMD_GETBIKERS = "GETBIKERS"
CMD_GETMAP = "GETMAP"
CMD_GETDELIVERIES = "GETDELIVERIES"
CMD_TAKE = "TAKE"
CMD_DELIVER = "DELIVER"
CMD_ENDTURN = "ENDTURN"
CMD_SCORE = "SCORE"

SERVER_OK = "OK"
SERVER_NOK = "NOK"
SERVER_NAME = "NAME"
SERVER_START = "START"
SERVER_ENDGAME = "ENDGAME"
